### ISSUE TITLE
Elisp fibonacci function not yet correct

### ISSUE THREAD

**Issue by samWson** [samWson/fibonacci#2]
I thought the Wikipedia supplied formula for calculating fibonnacci numbers simple. 
`Fn = (Fn - 1) + (Fn - 2)`
However I find my elisp function in the file fibonacci.el not working as expected.

These are the results my elisp function returns for a given argument where Fn = the arg:
- arg 1, returns -1 (I guess the first number is always 1?)
- arg 2, returns 1
- arg 3, returns 3
- arg 4, returns 5
- arg 5, returns 7
- arg 6, returns 9 

My sequence: -1, 1, 3, 5, 7, 9
The correct sequence: 1, 1, 2, 3, 5, 8...

I'm guessing I don't know how to correctly use the formula in the first place, therefore my elisp function will be wrong.

**Comment by jccarlson** [comment]
Hi sam, 

I submitted a pull request with a fixed version of your function, plus an alternative function that uses an iterative approach. The error in your code was that you were misinterpreting the Wikipedia definition of the Fibonacci sequence. The definition given on the wiki page is recursive, that is, the n-th Fibonacci number is the (n-1)th Fibonacci number plus the (n-2)th Fibonacci number, with the exception of the first and second numbers (n = 1 and n = 2), which are both defined as 1. The elisp function you implemented only returns the sum of (n - 1) and (n - 2), when it should be returning the sum of the function with (n-1) as an argument, and the function with (n - 2) as an argument.

**Comment by samWson** [comment]
Thanks for your response @jccarlson. I'll have a good look at it.
